### PR TITLE
90% Added style guide to handbook

### PR DESCRIPTION
**Pull request by danielmatthew**
- Changes to app typography work quite well within handbook too: still
legible and attractive without needing too much extra work.

- See attached screenshot of how the style guide page looks: 
screen shot 2015-07-06 at 11 29 05

…though needs a little fine-tuning.

### CODE REVIEW

**Comment by danielmatthew** [comment]
So just wondering: using an iframe to keep Bootstrap and app styles separate from those of the Handbook. Seems to be working a treat, though, miss the footnote and syntax highlighting GHFM offers.

**Comment by danielmatthew** [comment]
Sacked off the iframe approach to keep content as Markdown:

style-guide-jsbin

**Comment by danielmatthew** [comment]
Also wondering: this is quickly becoming a lengthy article. Would it be easier to comprehend if there were chapters for Typography, Colours, Patterns, etc.?

**Comment by jeremybaines** [comment]
Just spotted this! Wow this has moved on!!!!

An some point it would be nice to create a starting template, for internal, backend or hack day projects that gives you a basic menu, header, title, search, filters, table, pagination all in the right place. Maybe we save this somewhere with 'Talis Bootstrap'

**Comment by danielmatthew** [comment]
That's a good point you make @jeremybaines - and you'll be pleased to know that when our Bootstrap fork is updated and generated, it automatically updates its documentation and examples to reflect our own preferences. So folks will be able to take one of the existing templates and have a great starting point from which to build on.

**Comment by jeremybaines** [comment]
Should also apply the heading styles to the handbook itself

**Comment by danielmatthew** [comment]
@robotrobot Oh, that's the intention: should somebody really ~~want~~need to make something look like a header they can do so.

**Comment by danielmatthew** [comment]
fireshot capture - application style guide - engine_ - http___localhost_4000_topics_style-guide html

**Comment by jeremybaines** [comment]
:thumbsup:

**Pull request merged**
